version: "3.8"

services:
  api_agent:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8001:8001"
    env_file:
      - .env

  scraping_agent:
    build:
      context: .
      dockerfile: Dockerfile.scraping
    ports:
      - "8002:8002"
    env_file:
      - .env
      
  retriever-agent:
    build:
      context: .
      dockerfile: Dockerfile.retriever
    ports:
      - "8003:8001"
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env
    environment:
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - VECTOR_STORE_PATH=/app/data/vector_store
      - HOST=0.0.0.0
      - PORT=8001
    restart: unless-stopped

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "8004:8001"
    env_file:
      - .env
    depends_on:
      - api_agent
      - scraping_agent
      - retriever-agent
    environment:
      - API_AGENT_URL=http://api_agent:8001
      - SCRAPING_AGENT_URL=http://scraping_agent:8002
      - RETRIEVER_AGENT_URL=http://retriever-agent:8001
      - LANGUAGE_AGENT_URL=http://language_agent:8004
      - TIMEOUT=30
    restart: unless-stopped

  language_agent:
    build:
      context: .
      dockerfile: Dockerfile.language
    ports:
      - "8005:8004"
    env_file:
      - .env
    environment:
      - GEMINI_MODEL=gemini-flash
      - TIMEOUT=10
      - HOST=0.0.0.0
      - PORT=8004
    restart: unless-stopped

  voice_agent:
    build:
      context: .
      dockerfile: Dockerfile.voice
    ports:
      - "8006:8006"
    env_file:
      - .env
    depends_on:
      - orchestrator
    environment:
      - STT_PROVIDER=whisper
      - TTS_PROVIDER=gtts
      - MODEL_PATH_STT=/app/models/whisper
      - CACHE_DIR=/app/cache
      - VAD_AGGRESSIVENESS=2
      - RNNOISE_ENABLED=true
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api_agent
      - scraping_agent
      - retriever-agent
      - orchestrator
      - language_agent
