version: "3.8"

services:
  api_agent:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8001:8001"
    env_file:
      - .env

  scraping_agent:
    build:
      context: .
      dockerfile: Dockerfile.scraping
    ports:
      - "8002:8002"
    env_file:
      - .env
      
  retriever-agent:
    build:
      context: ../../
      dockerfile: Dockerfile.retriever
    ports:
      - "8003:8001"
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env
    environment:
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - VECTOR_STORE_PATH=/app/data/vector_store
      - HOST=0.0.0.0
      - PORT=8001
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api_agent
      - scraping_agent
      - retriever_agent
