version: "3.8"

services:
  api_agent:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8001:8001"
    env_file:
      - .env

  scraping_agent:
    build:
      context: .
      dockerfile: Dockerfile.scraping
    ports:
      - "8002:8002"
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api_agent
      - scraping_agent
